# Generated by Django 5.1 on 2024-08-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
